# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android/support -r features/android/helpers -r features/step_definitions -r features/android/pages
ios6:     PLATFORM=ios SDK_VERSION=6.0 -r features/support -r features/ios/support     -r features/ios/helpers     -r features/step_definitions -r features/ios/pages
